# permissions for end users to edit cidrclaimtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cidrclaimtemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controlplane
    app.kubernetes.io/part-of: controlplane
    app.kubernetes.io/managed-by: kustomize
  name: cidrclaimtemplate-editor-role
rules:
- apiGroups:
  - controlplane.miscord.win
  resources:
  - cidrclaimtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.miscord.win
  resources:
  - cidrclaimtemplates/status
  verbs:
  - get
