# permissions for end users to view cidrblocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cidrblock-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controlplane
    app.kubernetes.io/part-of: controlplane
    app.kubernetes.io/managed-by: kustomize
  name: cidrblock-viewer-role
rules:
- apiGroups:
  - controlplane.miscord.win
  resources:
  - cidrblocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.miscord.win
  resources:
  - cidrblocks/status
  verbs:
  - get
