// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Route is the predicate function for route builders.
type Route func(*sql.Selector)
