# permissions for end users to edit cniconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cniconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: toxfud
    app.kubernetes.io/part-of: toxfud
    app.kubernetes.io/managed-by: kustomize
  name: cniconfig-editor-role
rules:
- apiGroups:
  - client.miscord.win
  resources:
  - cniconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.miscord.win
  resources:
  - cniconfigs/status
  verbs:
  - get
