// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/miscord-dev/toxfu/persistent/ent/address"
	"github.com/miscord-dev/toxfu/persistent/ent/node"
	"github.com/miscord-dev/toxfu/persistent/ent/predicate"
	"github.com/miscord-dev/toxfu/persistent/ent/route"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (nu *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetPublicKey sets the "public_key" field.
func (nu *NodeUpdate) SetPublicKey(s string) *NodeUpdate {
	nu.mutation.SetPublicKey(s)
	return nu
}

// SetPublicDiscoKey sets the "public_disco_key" field.
func (nu *NodeUpdate) SetPublicDiscoKey(s string) *NodeUpdate {
	nu.mutation.SetPublicDiscoKey(s)
	return nu
}

// SetHostName sets the "host_name" field.
func (nu *NodeUpdate) SetHostName(s string) *NodeUpdate {
	nu.mutation.SetHostName(s)
	return nu
}

// SetOs sets the "os" field.
func (nu *NodeUpdate) SetOs(s string) *NodeUpdate {
	nu.mutation.SetOs(s)
	return nu
}

// SetGoos sets the "goos" field.
func (nu *NodeUpdate) SetGoos(s string) *NodeUpdate {
	nu.mutation.SetGoos(s)
	return nu
}

// SetGoarch sets the "goarch" field.
func (nu *NodeUpdate) SetGoarch(s string) *NodeUpdate {
	nu.mutation.SetGoarch(s)
	return nu
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (nu *NodeUpdate) SetLastUpdatedAt(t time.Time) *NodeUpdate {
	nu.mutation.SetLastUpdatedAt(t)
	return nu
}

// SetEndpoints sets the "endpoints" field.
func (nu *NodeUpdate) SetEndpoints(s []string) *NodeUpdate {
	nu.mutation.SetEndpoints(s)
	return nu
}

// SetState sets the "state" field.
func (nu *NodeUpdate) SetState(n node.State) *NodeUpdate {
	nu.mutation.SetState(n)
	return nu
}

// AddRouteIDs adds the "routes" edge to the Route entity by IDs.
func (nu *NodeUpdate) AddRouteIDs(ids ...int64) *NodeUpdate {
	nu.mutation.AddRouteIDs(ids...)
	return nu
}

// AddRoutes adds the "routes" edges to the Route entity.
func (nu *NodeUpdate) AddRoutes(r ...*Route) *NodeUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return nu.AddRouteIDs(ids...)
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (nu *NodeUpdate) AddAddressIDs(ids ...int64) *NodeUpdate {
	nu.mutation.AddAddressIDs(ids...)
	return nu
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (nu *NodeUpdate) AddAddresses(a ...*Address) *NodeUpdate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return nu.AddAddressIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nu *NodeUpdate) Mutation() *NodeMutation {
	return nu.mutation
}

// ClearRoutes clears all "routes" edges to the Route entity.
func (nu *NodeUpdate) ClearRoutes() *NodeUpdate {
	nu.mutation.ClearRoutes()
	return nu
}

// RemoveRouteIDs removes the "routes" edge to Route entities by IDs.
func (nu *NodeUpdate) RemoveRouteIDs(ids ...int64) *NodeUpdate {
	nu.mutation.RemoveRouteIDs(ids...)
	return nu
}

// RemoveRoutes removes "routes" edges to Route entities.
func (nu *NodeUpdate) RemoveRoutes(r ...*Route) *NodeUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return nu.RemoveRouteIDs(ids...)
}

// ClearAddresses clears all "addresses" edges to the Address entity.
func (nu *NodeUpdate) ClearAddresses() *NodeUpdate {
	nu.mutation.ClearAddresses()
	return nu
}

// RemoveAddressIDs removes the "addresses" edge to Address entities by IDs.
func (nu *NodeUpdate) RemoveAddressIDs(ids ...int64) *NodeUpdate {
	nu.mutation.RemoveAddressIDs(ids...)
	return nu
}

// RemoveAddresses removes "addresses" edges to Address entities.
func (nu *NodeUpdate) RemoveAddresses(a ...*Address) *NodeUpdate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return nu.RemoveAddressIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NodeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nu.hooks) == 0 {
		if err = nu.check(); err != nil {
			return 0, err
		}
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nu.check(); err != nil {
				return 0, err
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			if nu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NodeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NodeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NodeUpdate) check() error {
	if v, ok := nu.mutation.State(); ok {
		if err := node.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Node.state": %w`, err)}
		}
	}
	return nil
}

func (nu *NodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   node.Table,
			Columns: node.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: node.FieldID,
			},
		},
	}
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.PublicKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldPublicKey,
		})
	}
	if value, ok := nu.mutation.PublicDiscoKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldPublicDiscoKey,
		})
	}
	if value, ok := nu.mutation.HostName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldHostName,
		})
	}
	if value, ok := nu.mutation.Os(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldOs,
		})
	}
	if value, ok := nu.mutation.Goos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldGoos,
		})
	}
	if value, ok := nu.mutation.Goarch(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldGoarch,
		})
	}
	if value, ok := nu.mutation.LastUpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: node.FieldLastUpdatedAt,
		})
	}
	if value, ok := nu.mutation.Endpoints(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: node.FieldEndpoints,
		})
	}
	if value, ok := nu.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: node.FieldState,
		})
	}
	if nu.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !nu.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedAddressesIDs(); len(nodes) > 0 && !nu.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetPublicKey sets the "public_key" field.
func (nuo *NodeUpdateOne) SetPublicKey(s string) *NodeUpdateOne {
	nuo.mutation.SetPublicKey(s)
	return nuo
}

// SetPublicDiscoKey sets the "public_disco_key" field.
func (nuo *NodeUpdateOne) SetPublicDiscoKey(s string) *NodeUpdateOne {
	nuo.mutation.SetPublicDiscoKey(s)
	return nuo
}

// SetHostName sets the "host_name" field.
func (nuo *NodeUpdateOne) SetHostName(s string) *NodeUpdateOne {
	nuo.mutation.SetHostName(s)
	return nuo
}

// SetOs sets the "os" field.
func (nuo *NodeUpdateOne) SetOs(s string) *NodeUpdateOne {
	nuo.mutation.SetOs(s)
	return nuo
}

// SetGoos sets the "goos" field.
func (nuo *NodeUpdateOne) SetGoos(s string) *NodeUpdateOne {
	nuo.mutation.SetGoos(s)
	return nuo
}

// SetGoarch sets the "goarch" field.
func (nuo *NodeUpdateOne) SetGoarch(s string) *NodeUpdateOne {
	nuo.mutation.SetGoarch(s)
	return nuo
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (nuo *NodeUpdateOne) SetLastUpdatedAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetLastUpdatedAt(t)
	return nuo
}

// SetEndpoints sets the "endpoints" field.
func (nuo *NodeUpdateOne) SetEndpoints(s []string) *NodeUpdateOne {
	nuo.mutation.SetEndpoints(s)
	return nuo
}

// SetState sets the "state" field.
func (nuo *NodeUpdateOne) SetState(n node.State) *NodeUpdateOne {
	nuo.mutation.SetState(n)
	return nuo
}

// AddRouteIDs adds the "routes" edge to the Route entity by IDs.
func (nuo *NodeUpdateOne) AddRouteIDs(ids ...int64) *NodeUpdateOne {
	nuo.mutation.AddRouteIDs(ids...)
	return nuo
}

// AddRoutes adds the "routes" edges to the Route entity.
func (nuo *NodeUpdateOne) AddRoutes(r ...*Route) *NodeUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return nuo.AddRouteIDs(ids...)
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (nuo *NodeUpdateOne) AddAddressIDs(ids ...int64) *NodeUpdateOne {
	nuo.mutation.AddAddressIDs(ids...)
	return nuo
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (nuo *NodeUpdateOne) AddAddresses(a ...*Address) *NodeUpdateOne {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return nuo.AddAddressIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nuo *NodeUpdateOne) Mutation() *NodeMutation {
	return nuo.mutation
}

// ClearRoutes clears all "routes" edges to the Route entity.
func (nuo *NodeUpdateOne) ClearRoutes() *NodeUpdateOne {
	nuo.mutation.ClearRoutes()
	return nuo
}

// RemoveRouteIDs removes the "routes" edge to Route entities by IDs.
func (nuo *NodeUpdateOne) RemoveRouteIDs(ids ...int64) *NodeUpdateOne {
	nuo.mutation.RemoveRouteIDs(ids...)
	return nuo
}

// RemoveRoutes removes "routes" edges to Route entities.
func (nuo *NodeUpdateOne) RemoveRoutes(r ...*Route) *NodeUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return nuo.RemoveRouteIDs(ids...)
}

// ClearAddresses clears all "addresses" edges to the Address entity.
func (nuo *NodeUpdateOne) ClearAddresses() *NodeUpdateOne {
	nuo.mutation.ClearAddresses()
	return nuo
}

// RemoveAddressIDs removes the "addresses" edge to Address entities by IDs.
func (nuo *NodeUpdateOne) RemoveAddressIDs(ids ...int64) *NodeUpdateOne {
	nuo.mutation.RemoveAddressIDs(ids...)
	return nuo
}

// RemoveAddresses removes "addresses" edges to Address entities.
func (nuo *NodeUpdateOne) RemoveAddresses(a ...*Address) *NodeUpdateOne {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return nuo.RemoveAddressIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Node entity.
func (nuo *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	var (
		err  error
		node *Node
	)
	if len(nuo.hooks) == 0 {
		if err = nuo.check(); err != nil {
			return nil, err
		}
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nuo.check(); err != nil {
				return nil, err
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			if nuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NodeUpdateOne) check() error {
	if v, ok := nuo.mutation.State(); ok {
		if err := node.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Node.state": %w`, err)}
		}
	}
	return nil
}

func (nuo *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   node.Table,
			Columns: node.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: node.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.PublicKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldPublicKey,
		})
	}
	if value, ok := nuo.mutation.PublicDiscoKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldPublicDiscoKey,
		})
	}
	if value, ok := nuo.mutation.HostName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldHostName,
		})
	}
	if value, ok := nuo.mutation.Os(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldOs,
		})
	}
	if value, ok := nuo.mutation.Goos(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldGoos,
		})
	}
	if value, ok := nuo.mutation.Goarch(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: node.FieldGoarch,
		})
	}
	if value, ok := nuo.mutation.LastUpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: node.FieldLastUpdatedAt,
		})
	}
	if value, ok := nuo.mutation.Endpoints(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: node.FieldEndpoints,
		})
	}
	if value, ok := nuo.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: node.FieldState,
		})
	}
	if nuo.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !nuo.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RoutesTable,
			Columns: []string{node.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: route.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedAddressesIDs(); len(nodes) > 0 && !nuo.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AddressesTable,
			Columns: []string{node.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
