// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/miscord-dev/toxfu/persistent/ent/node"
	"github.com/miscord-dev/toxfu/persistent/ent/route"
)

// RouteCreate is the builder for creating a Route entity.
type RouteCreate struct {
	config
	mutation *RouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAddr sets the "addr" field.
func (rc *RouteCreate) SetAddr(s string) *RouteCreate {
	rc.mutation.SetAddr(s)
	return rc
}

// SetBits sets the "bits" field.
func (rc *RouteCreate) SetBits(i int) *RouteCreate {
	rc.mutation.SetBits(i)
	return rc
}

// SetID sets the "id" field.
func (rc *RouteCreate) SetID(i int64) *RouteCreate {
	rc.mutation.SetID(i)
	return rc
}

// SetHostID sets the "host" edge to the Node entity by ID.
func (rc *RouteCreate) SetHostID(id int64) *RouteCreate {
	rc.mutation.SetHostID(id)
	return rc
}

// SetNillableHostID sets the "host" edge to the Node entity by ID if the given value is not nil.
func (rc *RouteCreate) SetNillableHostID(id *int64) *RouteCreate {
	if id != nil {
		rc = rc.SetHostID(*id)
	}
	return rc
}

// SetHost sets the "host" edge to the Node entity.
func (rc *RouteCreate) SetHost(n *Node) *RouteCreate {
	return rc.SetHostID(n.ID)
}

// Mutation returns the RouteMutation object of the builder.
func (rc *RouteCreate) Mutation() *RouteMutation {
	return rc.mutation
}

// Save creates the Route in the database.
func (rc *RouteCreate) Save(ctx context.Context) (*Route, error) {
	var (
		err  error
		node *Route
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RouteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RouteCreate) SaveX(ctx context.Context) *Route {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RouteCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RouteCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RouteCreate) check() error {
	if _, ok := rc.mutation.Addr(); !ok {
		return &ValidationError{Name: "addr", err: errors.New(`ent: missing required field "Route.addr"`)}
	}
	if v, ok := rc.mutation.Addr(); ok {
		if err := route.AddrValidator(v); err != nil {
			return &ValidationError{Name: "addr", err: fmt.Errorf(`ent: validator failed for field "Route.addr": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Bits(); !ok {
		return &ValidationError{Name: "bits", err: errors.New(`ent: missing required field "Route.bits"`)}
	}
	return nil
}

func (rc *RouteCreate) sqlSave(ctx context.Context) (*Route, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (rc *RouteCreate) createSpec() (*Route, *sqlgraph.CreateSpec) {
	var (
		_node = &Route{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: route.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: route.FieldID,
			},
		}
	)
	_spec.OnConflict = rc.conflict
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.Addr(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: route.FieldAddr,
		})
		_node.Addr = value
	}
	if value, ok := rc.mutation.Bits(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: route.FieldBits,
		})
		_node.Bits = value
	}
	if nodes := rc.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   route.HostTable,
			Columns: []string{route.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: node.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.node_routes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Route.Create().
//		SetAddr(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RouteUpsert) {
//			SetAddr(v+v).
//		}).
//		Exec(ctx)
//
func (rc *RouteCreate) OnConflict(opts ...sql.ConflictOption) *RouteUpsertOne {
	rc.conflict = opts
	return &RouteUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rc *RouteCreate) OnConflictColumns(columns ...string) *RouteUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RouteUpsertOne{
		create: rc,
	}
}

type (
	// RouteUpsertOne is the builder for "upsert"-ing
	//  one Route node.
	RouteUpsertOne struct {
		create *RouteCreate
	}

	// RouteUpsert is the "OnConflict" setter.
	RouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetAddr sets the "addr" field.
func (u *RouteUpsert) SetAddr(v string) *RouteUpsert {
	u.Set(route.FieldAddr, v)
	return u
}

// UpdateAddr sets the "addr" field to the value that was provided on create.
func (u *RouteUpsert) UpdateAddr() *RouteUpsert {
	u.SetExcluded(route.FieldAddr)
	return u
}

// SetBits sets the "bits" field.
func (u *RouteUpsert) SetBits(v int) *RouteUpsert {
	u.Set(route.FieldBits, v)
	return u
}

// UpdateBits sets the "bits" field to the value that was provided on create.
func (u *RouteUpsert) UpdateBits() *RouteUpsert {
	u.SetExcluded(route.FieldBits)
	return u
}

// AddBits adds v to the "bits" field.
func (u *RouteUpsert) AddBits(v int) *RouteUpsert {
	u.Add(route.FieldBits, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(route.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *RouteUpsertOne) UpdateNewValues() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(route.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Route.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *RouteUpsertOne) Ignore() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RouteUpsertOne) DoNothing() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RouteCreate.OnConflict
// documentation for more info.
func (u *RouteUpsertOne) Update(set func(*RouteUpsert)) *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetAddr sets the "addr" field.
func (u *RouteUpsertOne) SetAddr(v string) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetAddr(v)
	})
}

// UpdateAddr sets the "addr" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateAddr() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateAddr()
	})
}

// SetBits sets the "bits" field.
func (u *RouteUpsertOne) SetBits(v int) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetBits(v)
	})
}

// AddBits adds v to the "bits" field.
func (u *RouteUpsertOne) AddBits(v int) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.AddBits(v)
	})
}

// UpdateBits sets the "bits" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateBits() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateBits()
	})
}

// Exec executes the query.
func (u *RouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RouteCreateBulk is the builder for creating many Route entities in bulk.
type RouteCreateBulk struct {
	config
	builders []*RouteCreate
	conflict []sql.ConflictOption
}

// Save creates the Route entities in the database.
func (rcb *RouteCreateBulk) Save(ctx context.Context) ([]*Route, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Route, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RouteCreateBulk) SaveX(ctx context.Context) []*Route {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RouteCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RouteCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Route.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RouteUpsert) {
//			SetAddr(v+v).
//		}).
//		Exec(ctx)
//
func (rcb *RouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *RouteUpsertBulk {
	rcb.conflict = opts
	return &RouteUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rcb *RouteCreateBulk) OnConflictColumns(columns ...string) *RouteUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RouteUpsertBulk{
		create: rcb,
	}
}

// RouteUpsertBulk is the builder for "upsert"-ing
// a bulk of Route nodes.
type RouteUpsertBulk struct {
	create *RouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(route.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *RouteUpsertBulk) UpdateNewValues() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(route.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *RouteUpsertBulk) Ignore() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RouteUpsertBulk) DoNothing() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RouteCreateBulk.OnConflict
// documentation for more info.
func (u *RouteUpsertBulk) Update(set func(*RouteUpsert)) *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetAddr sets the "addr" field.
func (u *RouteUpsertBulk) SetAddr(v string) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetAddr(v)
	})
}

// UpdateAddr sets the "addr" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateAddr() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateAddr()
	})
}

// SetBits sets the "bits" field.
func (u *RouteUpsertBulk) SetBits(v int) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetBits(v)
	})
}

// AddBits adds v to the "bits" field.
func (u *RouteUpsertBulk) AddBits(v int) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.AddBits(v)
	})
}

// UpdateBits sets the "bits" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateBits() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateBits()
	})
}

// Exec executes the query.
func (u *RouteUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
