// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/miscord-dev/toxfu/persistent/ent/address"
	"github.com/miscord-dev/toxfu/persistent/ent/route"
	"github.com/miscord-dev/toxfu/persistent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescAddr is the schema descriptor for addr field.
	addressDescAddr := addressFields[1].Descriptor()
	// address.AddrValidator is a validator for the "addr" field. It is called by the builders before save.
	address.AddrValidator = addressDescAddr.Validators[0].(func(string) error)
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescAddr is the schema descriptor for addr field.
	routeDescAddr := routeFields[1].Descriptor()
	// route.AddrValidator is a validator for the "addr" field. It is called by the builders before save.
	route.AddrValidator = routeDescAddr.Validators[0].(func(string) error)
}
