apiVersion: controlplane.miscord.win/v1alpha1
kind: CIDRClaim
metadata:
  labels:
    app.kubernetes.io/name: cidrclaim
    app.kubernetes.io/instance: cidrclaim-sample
    app.kubernetes.io/part-of: controlplane
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controlplane
  name: cidrclaim-sample
spec:
  # TODO(user): Add fields here
