// Code generated by MockGen. DO NOT EDIT.
// Source: disco.go

// Package mock_disco is a generated GoMock package.
package mock_disco

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	disco "github.com/miscord-dev/tetrapod/disco"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(pkt *disco.EncryptedDiscoPacket) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", pkt)
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(pkt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), pkt)
}
