// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "public_key", Type: field.TypeString, Unique: true},
		{Name: "public_disco_key", Type: field.TypeString, Unique: true},
		{Name: "host_name", Type: field.TypeString},
		{Name: "os", Type: field.TypeString},
		{Name: "goos", Type: field.TypeString},
		{Name: "goarch", Type: field.TypeString},
		{Name: "last_updated_at", Type: field.TypeString},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"online", "offline", "disabled"}},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NodesTable,
	}
)

func init() {
}
