---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - client.miscord.win
  resources:
  - ExtraPodCIDRSyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.miscord.win
  resources:
  - ExtraPodCIDRSyncs/finalizers
  verbs:
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - ExtraPodCIDRSyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - cidrclaimers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.miscord.win
  resources:
  - cidrclaimers/finalizers
  verbs:
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - cidrclaimers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - peernodesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.miscord.win
  resources:
  - peernodesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - peernodesyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - peerssyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.miscord.win
  resources:
  - peerssyncs/finalizers
  verbs:
  - update
- apiGroups:
  - client.miscord.win
  resources:
  - peerssyncs/status
  verbs:
  - get
  - patch
  - update
